# Generated by Django 3.1.1 on 2020-11-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'sent'), ('accepted', 'accepted')], max_length=8),
        ),
    ]
